// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Studentmanagement.Entities
{
    public partial class Employeemanagement
    {
        [Key]
        [Column("Student_Id")]
        public int StudentId { get; set; }
        [Required]
        [StringLength(20)]
        public string Fullname { get; set; }
        [Required]
        [StringLength(20)]
        public string Username { get; set; }
        [Required]
        [StringLength(20)]
        public string Email { get; set; }
        public int Department { get; set; }
        [Required]
        [StringLength(20)]
        public string Work { get; set; }
        [Required]
        [StringLength(20)]
        public string Address { get; set; }
        [Required]
        [Column("phonenumber")]
        [StringLength(15)]
        public string Phonenumber { get; set; }
        [Required]
        [StringLength(6)]
        public string Gender { get; set; }
        [Column("Is_deleted")]
        public bool IsDeleted { get; set; }
        [Column("Created_Time_stamp", TypeName = "datetime")]
        public DateTime CreatedTimeStamp { get; set; }
        [Column("Updated_Time_stamp", TypeName = "datetime")]
        public DateTime UpdatedTimeStamp { get; set; }
    }
}