// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Studentmanagement.Entities
{
    [Table("studentinfo")]
    public partial class Studentinfo
    {
        [Key]
        public int StudentId { get; set; }
        [Required]
        [StringLength(20)]
        public string Name { get; set; }
        [Required]
        [StringLength(20)]
        public string Email { get; set; }
        [Required]
        [StringLength(5)]
        public string DepartmentName { get; set; }
        [Required]
        [StringLength(6)]
        public string Gender { get; set; }
        [Column("Created_Time_stamp", TypeName = "datetime")]
        public DateTime CreatedTimeStamp { get; set; }
        [Column("Updated_Time_stamp", TypeName = "datetime")]
        public DateTime UpdatedTimeStamp { get; set; }
        [Column("Is_deleted")]
        public bool IsDeleted { get; set; }
    }
}